import { EventTheme } from '../types';

export const DEFAULT_THEMES: EventTheme[] = [
  {
    id: 'wedding_elegance',
    name: 'Pernikahan Elegir',
    category: 'wedding',
    frameColor: '#FFFDF9',
    textColor: '#3D312A',
    backgroundColor: '#F7F3ED',
    bgPattern: 'solid',
    accentColor: '#D4AF37',
    fontFamily: 'serif',
    eventTitle: 'Sarah & Alex Wedding',
    eventSubtitle: 'The Beginning of Forever',
    eventDate: '08.08.2026',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'luxury_wedding',
    homeCtaText: 'SENTUH UNTUK MULAI FOTO',
    homeCtaColor: 'royal_gold',
    homeBgBlur: 'light',
  },
  {
    id: 'retro_y2k',
    name: 'Y2K Party Retro',
    category: 'retro',
    frameColor: '#181825',
    textColor: '#FF70A6',
    backgroundColor: '#0F0F1A',
    bgPattern: 'solid',
    accentColor: '#70D6FF',
    fontFamily: 'display',
    eventTitle: '21st Birthday Bash',
    eventSubtitle: 'Y2K VIBES ONLY • NO FILTER NEEDED',
    eventDate: '08/08/2026',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'billboard',
    homeCtaText: 'TAP TO START PHOTOBOOTH',
    homeCtaColor: 'rose_amber',
    homeBgBlur: 'light',
  },
  {
    id: 'cyber_neon',
    name: 'Neon Night Club',
    category: 'party',
    frameColor: '#05050A',
    textColor: '#00F5D4',
    backgroundColor: '#0A0A12',
    bgPattern: 'solid',
    accentColor: '#F72585',
    fontFamily: 'mono',
    eventTitle: 'NEON NIGHT 2026',
    eventSubtitle: 'Jakarta Midnight Rave',
    eventDate: '08•08•26',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'neon_party',
    homeCtaText: 'TOUCH TO START RAVE',
    homeCtaColor: 'cyber_neon',
    homeBgBlur: 'heavy',
  },
  {
    id: 'pastel_romance',
    name: 'Pastel Cute & Sweet',
    category: 'birthday',
    frameColor: '#FFF0F5',
    textColor: '#5E4B56',
    backgroundColor: '#FFD6E0',
    bgPattern: 'solid',
    accentColor: '#FFB3C1',
    fontFamily: 'handwriting',
    eventTitle: 'Sweet Sixteen Amelia',
    eventSubtitle: 'Spread Love & Smiles',
    eventDate: '8 Agustus 2026',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'classic',
    homeCtaText: 'SENTUH UNTUK MULAI',
    homeCtaColor: 'rose_amber',
    homeBgBlur: 'light',
  },
  {
    id: 'classic_mono',
    name: 'Monokrom Studio',
    category: 'minimal',
    frameColor: '#FFFFFF',
    textColor: '#111111',
    backgroundColor: '#E5E5E5',
    bgPattern: 'solid',
    accentColor: '#333333',
    fontFamily: 'sans',
    eventTitle: 'SNAPBOOTH STUDIO',
    eventSubtitle: 'Classic Black & White Collection',
    eventDate: '2026.08.08',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'minimal',
    homeCtaText: 'START SESSION',
    homeCtaColor: 'slate_dark',
    homeBgBlur: 'none',
  },
  {
    id: 'corporate_gala',
    name: 'Corporate Annual Gala',
    category: 'corporate',
    frameColor: '#1E293B',
    textColor: '#F8FAFC',
    backgroundColor: '#0F172A',
    bgPattern: 'solid',
    accentColor: '#38BDF8',
    fontFamily: 'sans',
    eventTitle: 'Tech Summit 2026',
    eventSubtitle: 'Connecting Innovation & Future',
    eventDate: 'AUG 08, 2026',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'kiosk_vertical',
    homeCtaText: 'PRESS TO START',
    homeCtaColor: 'emerald',
    homeBgBlur: 'light',
  },
  {
    id: 'korean_receipt_style',
    name: 'Korean Receipt Photo (영수증)',
    category: 'retro',
    frameColor: '#FAF7F2',
    textColor: '#1A1A1A',
    backgroundColor: '#EAE6DF',
    bgPattern: 'solid',
    accentColor: '#1A1A1A',
    fontFamily: 'mono',
    eventTitle: 'KR RECEIPT PHOTOBOOTH',
    eventSubtitle: 'SPECIAL MEMORIES RECEIPT',
    eventDate: '2026.08.08 - 20:00:00',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'minimal',
    homeCtaText: 'PRINT RECEIPT PHOTO',
    homeCtaColor: 'slate_dark',
    homeBgBlur: 'none',
  },
  {
    id: 'car_free_day_receipt',
    name: 'Car Free Day (CFD) Receipt 🚲',
    category: 'retro',
    frameColor: '#FAF8F5',
    textColor: '#111827',
    backgroundColor: '#DCFCE7',
    bgPattern: 'solid',
    accentColor: '#16A34A',
    fontFamily: 'mono',
    eventTitle: 'JAKARTA CAR FREE DAY',
    eventSubtitle: 'SUNDAY MORNING HEALTH & VIBES 🏃🚲',
    eventDate: 'MINGGU, 08 AGUSTUS 2026',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'minimal',
    homeCtaText: 'FOTO STRUK CAR FREE DAY',
    homeCtaColor: 'emerald',
    homeBgBlur: 'none',
  },
];

export const STICKER_PACKS = [
  {
    name: 'Pesta & Lucu',
    stickers: ['👑', '🕶️', '🎂', '🥳', '🎉', '💖', '⭐', '🎈', '✨', '🔥', '🎀', '🥂'],
  },
  {
    name: 'Aksesoris & Topi',
    stickers: ['🤠', '🎩', '🤡', '🥸', '🎧', '👾', '🌈', '🦩', '🌸', '🌼', '🦋', '🧸'],
  },
  {
    name: 'Teks & Badge',
    stickers: ['💯', 'VIP', 'BESTIES', 'LOVE', 'LOL', 'OMG', 'XOXO', 'CUTE', 'SWAG', 'PARTY'],
  },
];
