import { EventTheme } from '../types';

export const DEFAULT_THEMES: EventTheme[] = [
  {
    id: 'wedding_elegance',
    name: 'Pernikahan Elegir',
    category: 'wedding',
    frameColor: '#FFFDF9',
    textColor: '#3D312A',
    backgroundColor: '#F7F3ED',
    bgPattern: 'solid',
    accentColor: '#D4AF37',
    fontFamily: 'serif',
    eventTitle: 'Sarah & Alex Wedding',
    eventSubtitle: 'The Beginning of Forever',
    eventDate: '08.08.2026',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'luxury_wedding',
    homeCtaText: 'SENTUH UNTUK MULAI FOTO',
    homeCtaColor: 'royal_gold',
    homeBgBlur: 'light',
  },
  {
    id: 'retro_y2k',
    name: 'Y2K Party Retro',
    category: 'retro',
    frameColor: '#181825',
    textColor: '#FF70A6',
    backgroundColor: '#0F0F1A',
    bgPattern: 'solid',
    accentColor: '#70D6FF',
    fontFamily: 'display',
    eventTitle: '21st Birthday Bash',
    eventSubtitle: 'Y2K VIBES ONLY • NO FILTER NEEDED',
    eventDate: '08/08/2026',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'billboard',
    homeCtaText: 'TAP TO START PHOTOBOOTH',
    homeCtaColor: 'rose_amber',
    homeBgBlur: 'light',
  },
  {
    id: 'cyber_neon',
    name: 'Neon Night Club',
    category: 'party',
    frameColor: '#05050A',
    textColor: '#00F5D4',
    backgroundColor: '#0A0A12',
    bgPattern: 'solid',
    accentColor: '#F72585',
    fontFamily: 'mono',
    eventTitle: 'NEON NIGHT 2026',
    eventSubtitle: 'Jakarta Midnight Rave',
    eventDate: '08•08•26',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'neon_party',
    homeCtaText: 'TOUCH TO START RAVE',
    homeCtaColor: 'cyber_neon',
    homeBgBlur: 'heavy',
  },
  {
    id: 'pastel_romance',
    name: 'Pastel Cute & Sweet',
    category: 'birthday',
    frameColor: '#FFF0F5',
    textColor: '#5E4B56',
    backgroundColor: '#FFD6E0',
    bgPattern: 'solid',
    accentColor: '#FFB3C1',
    fontFamily: 'handwriting',
    eventTitle: 'Sweet Sixteen Amelia',
    eventSubtitle: 'Spread Love & Smiles',
    eventDate: '8 Agustus 2026',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'classic',
    homeCtaText: 'SENTUH UNTUK MULAI',
    homeCtaColor: 'rose_amber',
    homeBgBlur: 'light',
  },
  {
    id: 'classic_mono',
    name: 'Monokrom Studio',
    category: 'minimal',
    frameColor: '#FFFFFF',
    textColor: '#111111',
    backgroundColor: '#E5E5E5',
    bgPattern: 'solid',
    accentColor: '#333333',
    fontFamily: 'sans',
    eventTitle: 'SNAPBOTH RECEIPT',
    eventSubtitle: 'Classic Black & White Collection',
    eventDate: '2026.08.08',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'minimal',
    homeCtaText: 'START SESSION',
    homeCtaColor: 'slate_dark',
    homeBgBlur: 'none',
  },
  {
    id: 'corporate_gala',
    name: 'Corporate Annual Gala',
    category: 'corporate',
    frameColor: '#1E293B',
    textColor: '#F8FAFC',
    backgroundColor: '#0F172A',
    bgPattern: 'solid',
    accentColor: '#38BDF8',
    fontFamily: 'sans',
    eventTitle: 'Tech Summit 2026',
    eventSubtitle: 'Connecting Innovation & Future',
    eventDate: 'AUG 08, 2026',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'kiosk_vertical',
    homeCtaText: 'PRESS TO START',
    homeCtaColor: 'emerald',
    homeBgBlur: 'light',
  },
  {
    id: 'korean_receipt_style',
    name: 'Korean Receipt Photo (영수증)',
    category: 'retro',
    frameColor: '#FAF7F2',
    textColor: '#1A1A1A',
    backgroundColor: '#EAE6DF',
    bgPattern: 'solid',
    accentColor: '#1A1A1A',
    fontFamily: 'mono',
    eventTitle: 'KR RECEIPT PHOTOBOOTH',
    eventSubtitle: 'SPECIAL MEMORIES RECEIPT',
    eventDate: '2026.08.08 - 20:00:00',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'minimal',
    homeCtaText: 'PRINT RECEIPT PHOTO',
    homeCtaColor: 'slate_dark',
    homeBgBlur: 'none',
  },
  {
    id: 'car_free_day_receipt',
    name: 'Car Free Day (CFD) Receipt 🚲',
    category: 'retro',
    frameColor: '#FAF8F5',
    textColor: '#111827',
    backgroundColor: '#DCFCE7',
    bgPattern: 'solid',
    accentColor: '#16A34A',
    fontFamily: 'mono',
    eventTitle: 'JAKARTA CAR FREE DAY',
    eventSubtitle: 'SUNDAY MORNING HEALTH & VIBES 🏃🚲',
    eventDate: 'MINGGU, 08 AGUSTUS 2026',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'minimal',
    homeCtaText: 'FOTO STRUK CAR FREE DAY',
    homeCtaColor: 'emerald',
    homeBgBlur: 'none',
  },
  {
    id: 'artisan_cafe',
    name: 'Artisan Coffee & Cafe ☕',
    category: 'cafe',
    frameColor: '#3C2A21',
    textColor: '#F5EBE0',
    backgroundColor: '#1E120B',
    bgPattern: 'solid',
    accentColor: '#D5CEA3',
    fontFamily: 'serif',
    eventTitle: 'The Daily Grind Cafe & Roastery',
    eventSubtitle: 'Fresh Brews • Artisanal Coffee • Good Vibes ☕',
    eventDate: 'EST. 2026 • JAKARTA',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'classic',
    homeCtaText: 'SENTUH UNTUK FOTO DI CAFE',
    homeCtaColor: 'rose_amber',
    homeBgBlur: 'light',
  },
  {
    id: 'matcha_bakery_cafe',
    name: 'Cozy Matcha & Bakery 🍵',
    category: 'cafe',
    frameColor: '#E8ECD7',
    textColor: '#2D3A27',
    backgroundColor: '#F2F5EB',
    bgPattern: 'solid',
    accentColor: '#7E8D61',
    fontFamily: 'sans',
    eventTitle: 'Matcha & Bloom Cafe',
    eventSubtitle: 'Handcrafted Drinks & Fresh Croissants 🥐',
    eventDate: 'EVERYDAY FRESH • 2026',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'classic',
    homeCtaText: 'PESAN & FOTO MEMORY CAFE',
    homeCtaColor: 'emerald',
    homeBgBlur: 'light',
  },
  {
    id: 'fine_dining_restaurant',
    name: 'Bistro & Fine Dining 🍷',
    category: 'restaurant',
    frameColor: '#1C0D12',
    textColor: '#F3E8EE',
    backgroundColor: '#14090E',
    bgPattern: 'solid',
    accentColor: '#E5C378',
    fontFamily: 'serif',
    eventTitle: 'Le Jardin Bistro & Grill',
    eventSubtitle: 'Bon Appétit • Fine Culinary & Memories 🍷',
    eventDate: 'SPECIAL DINNER • 2026',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'luxury_wedding',
    homeCtaText: 'CAPTURE DINING MOMENT',
    homeCtaColor: 'royal_gold',
    homeBgBlur: 'heavy',
  },
  {
    id: 'italian_trattoria',
    name: 'Italian Trattoria & Pizza 🍕',
    category: 'restaurant',
    frameColor: '#FFFDF7',
    textColor: '#9A1F24',
    backgroundColor: '#F9F3EA',
    bgPattern: 'solid',
    accentColor: '#2E6F40',
    fontFamily: 'serif',
    eventTitle: "Nonna's Trattoria & Pizzeria",
    eventSubtitle: 'Authentic Pasta, Woodfired Pizza & Wine 🍝',
    eventDate: 'DELIZIOSO • 2026',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'classic',
    homeCtaText: 'START DINING PHOTOBOOTH',
    homeCtaColor: 'rose_amber',
    homeBgBlur: 'none',
  },
  {
    id: 'retro_diner_bistro',
    name: 'Retro American Diner 🍔',
    category: 'restaurant',
    frameColor: '#FDF6F0',
    textColor: '#D90429',
    backgroundColor: '#111827',
    bgPattern: 'solid',
    accentColor: '#EF233C',
    fontFamily: 'display',
    eventTitle: 'Route 66 Diner & Shakes',
    eventSubtitle: 'Juicy Burgers • Milkshakes • Classic Jukebox 🎵',
    eventDate: 'SINCE 1950 • VINTAGE DINER',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'billboard',
    homeCtaText: 'SNAP YOUR DINER PHOTO',
    homeCtaColor: 'rose_amber',
    homeBgBlur: 'light',
  },
  {
    id: 'sweet_gelato_dessert',
    name: 'Gelato & Dessert Lounge 🍨',
    category: 'cafe',
    frameColor: '#FFF0F5',
    textColor: '#5E4B56',
    backgroundColor: '#FFD6E0',
    bgPattern: 'solid',
    accentColor: '#FFB3C1',
    fontFamily: 'handwriting',
    eventTitle: 'Sweet Scoops Gelato Lounge',
    eventSubtitle: 'Sweet Desserts & Unforgettable Smiles ✨',
    eventDate: 'DELICIOUS MOMENTS • 2026',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'neon_party',
    homeCtaText: 'AMBIL FOTO SWEET GELATO',
    homeCtaColor: 'rose_amber',
    homeBgBlur: 'light',
  },
  {
    id: 'vogue_fashion_magazine',
    name: 'VOGUE Fashion Editorial 📖',
    category: 'magazine',
    frameColor: '#0F0F0F',
    textColor: '#FAF8F5',
    backgroundColor: '#050505',
    bgPattern: 'solid',
    accentColor: '#D4AF37',
    fontFamily: 'serif',
    eventTitle: 'VOGUE EDITORIAL',
    eventSubtitle: 'SPRING / SUMMER SPECIAL COVER STORY • EXCLUSIVE',
    eventDate: 'VOL. 2026 • LIMITED EDITION',
    showDateBadge: true,
    borderStyle: 'thin',
    homeStyle: 'luxury_wedding',
    homeCtaText: 'FOTO COVER MAJALAH VOGUE',
    homeCtaColor: 'royal_gold',
    homeBgBlur: 'heavy',
  },
  {
    id: 'pop_trend_magazine',
    name: 'POP Culture & Aesthetic 🎨',
    category: 'magazine',
    frameColor: '#FFFCF7',
    textColor: '#E63946',
    backgroundColor: '#1D3557',
    bgPattern: 'solid',
    accentColor: '#F4A261',
    fontFamily: 'display',
    eventTitle: 'POP CULTURE MAG',
    eventSubtitle: 'THE YOUTH & ART ISSUE • FEATURING YOU ✨',
    eventDate: 'ISSUE 08 • AUGUST 2026',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'billboard',
    homeCtaText: 'AMBIL FOTO COVER MAJALAH',
    homeCtaColor: 'rose_amber',
    homeBgBlur: 'light',
  },
  {
    id: 'wanderlust_travel_magazine',
    name: 'WANDERLUST Travel & Life ✈️',
    category: 'magazine',
    frameColor: '#F4F1EA',
    textColor: '#2B2D42',
    backgroundColor: '#D8E2DC',
    bgPattern: 'solid',
    accentColor: '#8D99AE',
    fontFamily: 'sans',
    eventTitle: 'WANDERLUST TRAVEL',
    eventSubtitle: 'EXPLORE THE WORLD • MEMORIES & DESTINATIONS 🌿',
    eventDate: 'SUMMER ESCAPE 2026',
    showDateBadge: true,
    borderStyle: 'none',
    homeStyle: 'minimal',
    homeCtaText: 'START TRAVEL MAGAZINE PHOTO',
    homeCtaColor: 'emerald',
    homeBgBlur: 'none',
  },
  {
    id: 'supermarket_retail_receipt',
    name: 'Supermarket & Mart Receipt 🛒',
    category: 'receipt',
    frameColor: '#FFFDF9',
    textColor: '#1A1D20',
    backgroundColor: '#111827',
    bgPattern: 'solid',
    accentColor: '#2563EB',
    fontFamily: 'mono',
    eventTitle: 'HAPPY MART SUPERMARKET',
    eventSubtitle: 'OFFICIAL PURCHASE RECEIPT • THANK YOU FOR SHOPPING',
    eventDate: 'INV/2026/08/08-99',
    showDateBadge: true,
    borderStyle: 'dashed',
    homeStyle: 'kiosk_vertical',
    homeCtaText: 'AMBIL FOTO STRUK BELANJA',
    homeCtaColor: 'rose_amber',
    homeBgBlur: 'none',
  },
  {
    id: 'bistro_cafe_receipt',
    name: 'Cafe Coffee Shop Receipt ☕',
    category: 'receipt',
    frameColor: '#FDFBF7',
    textColor: '#292524',
    backgroundColor: '#1C1917',
    bgPattern: 'solid',
    accentColor: '#D97706',
    fontFamily: 'mono',
    eventTitle: 'THE COFFEE ROASTERY & BAKERY',
    eventSubtitle: 'WARM BREWS & FRESH MEMORIES • STRUK KASIR ☕',
    eventDate: 'ORDER #CAFE-2026',
    showDateBadge: true,
    borderStyle: 'dashed',
    homeStyle: 'classic',
    homeCtaText: 'AMBIL FOTO STRUK CAFE',
    homeCtaColor: 'rose_amber',
    homeBgBlur: 'light',
  },
  {
    id: 'boutique_receipt',
    name: 'Boutique & Luxury Receipt 🛍️',
    category: 'receipt',
    frameColor: '#FAFAFA',
    textColor: '#09090B',
    backgroundColor: '#18181B',
    bgPattern: 'solid',
    accentColor: '#E11D48',
    fontFamily: 'mono',
    eventTitle: 'MAISON DE LUXE BOUTIQUE',
    eventSubtitle: 'EXCLUSIVITY & ELEGANCE • OFFICIAL SALES SLIP 🛍️',
    eventDate: 'TRANSACTION #LUXE-889',
    showDateBadge: true,
    borderStyle: 'dashed',
    homeStyle: 'luxury_wedding',
    homeCtaText: 'FOTO STRUK BOUTIQUE',
    homeCtaColor: 'royal_gold',
    homeBgBlur: 'heavy',
  },
];

export const STICKER_PACKS = [
  {
    name: 'Pesta & Lucu',
    stickers: ['👑', '🕶️', '🎂', '🥳', '🎉', '💖', '⭐', '🎈', '✨', '🔥', '🎀', '🥂'],
  },
  {
    name: 'Majalah & Struk 📖🛒',
    stickers: ['📖', '📰', '🛒', '🛍️', '🧾', '🏷️', '💸', '💳', '✨', '🌟', '📸', '⚡'],
  },
  {
    name: 'Cafe & Kuliner ☕🍰',
    stickers: ['☕', '🍵', '🥐', '🍰', '🍕', '🍝', '🍔', '🍟', '🍷', '🥂', '🍨', '🍩', '🧋', '🍳', '🥞', '🥨'],
  },
  {
    name: 'Aksesoris & Topi',
    stickers: ['🤠', '🎩', '🤡', '🥸', '🎧', '👾', '🌈', '🦩', '🌸', '🌼', '🦋', '🧸'],
  },
  {
    name: 'Teks & Badge',
    stickers: ['💯', 'VIP', 'BESTIES', 'LOVE', 'LOL', 'OMG', 'XOXO', 'CUTE', 'SWAG', 'PARTY'],
  },
];
